version: '3.9'

services:
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: newsdb
        volumes:
            - mongo-data:/data/db

    scrapper-service:   
        build:
            context: ./scrapper-service
        container_name: scrapper
        restart: unless-stopped
        depends_on:
            - mongo
        env_file:
            - .env
        ports:
            - "8001:8001"
        networks:
            - app-network

    api-service:
        build:
            context: ./api-service
        container_name: api
        restart: unless-stopped
        depends_on:
            - mongo
        env_file:
            - .env
        ports:
            - "5001:5000"
        networks:
            - app-network

volumes:
    mongo-data:

networks:
    app-network:
        driver: bridge