# Predefined RSS Feeds for Turkey
PRESET_FEEDS = {
    "TRT_Manşet": "https://www.trthaber.com/manset.rss",
    "TRT_SonDakika": "https://www.trthaber.com/sondakika.rss",
    "CNNTurk_Tum": "https://www.cnnturk.com/feed/rss/all/news",
    "HaberTurk_Gundem": "https://www.haberturk.com/rss/manset.xml",
    "HaberTurk_SonDakika": "https://www.haberturk.com/rss/sondakika.xml",
    "NTV_SonDakika": "https://www.ntv.com.tr/son-dakika.rss",
    "NTV_Gundem": "https://www.ntv.com.tr/gundem.rss",
    "Sozcu_Gundem": "https://www.sozcu.com.tr/rss/gundem.xml",
    "Sozcu_Dunya": "https://www.sozcu.com.tr/rss/dunya.xml",
    "Milliyet_SonDakika": "https://www.milliyet.com.tr/rss/rssNew/sondakikaRss.xml",
    "Milliyet_Gundem": "https://www.milliyet.com.tr/rss/rssNew/gundemRss.xml",
    "Sabah_SonDakika": "https://www.sabah.com.tr/rss/sondakika.xml",
    "Sabah_Gundem": "https://www.sabah.com.tr/rss/gundem.xml",
    "Hurriyet_Gundem": "https://www.hurriyet.com.tr/rss/gundem/",
    "Hurriyet_SonDakika": "https://www.hurriyet.com.tr/rss/son-dakika/",
    "Cumhuriyet_SonDakika": "https://www.cumhuriyet.com.tr/rss/son-dakika.xml",
    "Cumhuriyet_Gundem": "https://www.cumhuriyet.com.tr/rss/gundem.xml",
    "EnSonHaber_SonDakika": "https://www.ensonhaber.com/rss/ensonhaber.xml",
    "YeniSafak_Gundem": "https://www.yenisafak.com/rss?xml=gundem",
    "YeniSafak_Dunya": "https://www.yenisafak.com/rss?xml=dunya",
    "AHaber_SonDakika": "https://www.ahaber.com.tr/rss/son-dakika.xml",
}
